package enums;

public enum DatosArchivoTramaEnum {
	TIPO_DOCUMENTO_FACTURADOR("dfac"), 
	TIPO_CARACTERISTICAS_GENERALES_PRESTACION("date"),
	TIPO_DETALLE_SERVICIOS("dser"),
	TIPO_PRODUCTOS_FARMACIA("dfar"),
	TIPO_DENTAL("dden"),
	MECANISMO_PAGO("01"),
	SUB_MECANISMO_PAGO("999"),
	MONTO_PRE_PACTADO("0.00"),
	FECHA_PRE_PACTADO(" "),
	INDICADOR_GLOBAL("N"),
	TIPO_NOTA_SIN_REFERENCIA("N"),
	CODIGO_PRESTACION_INTERNO("000091068c"),
	TIPO_AFILIACION_PACIENTE("1"),
	DOCUMENTO_AUTORIZACION("01"),
	SEGUNDO_NUMERO_AUTORIZACION("99"),
	SUB_TIPO_COBERTURA("  CS"),
	TIPO_DOCUMENTO_MEDICO("1"),
	TIPO_EGRESO_HOSPITALARIO("01"),
	TIPO_CLASIFICACION_PROCEDIMIENTO("02"),
	SERVICIO_EXENTO_IMPUESTOS("A"),
	CODIGO_RUGRO("16"),
	CATALAGO_PRODUCTO("C"),
	PRODUCTO_EXENTO_IMPUESTOS("A"),
	GUIA_FARMACIA("XXXXXXXXXXXX"),
	CODIGO_PRODUCTO_IAFAS("99999"),
	CANTIDAD_PRESTACIONES_SALUD("1");
	
	private final String value;

	private DatosArchivoTramaEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}