package enums;

public enum NombreEntidadEnum {

    TIPO_PROFESIONAL("Tipo de profesional"),
    ESPECIALIDAD("Especialidad"),
    EMPRESA("Empresa"),
    MEDICO("Médico"),
    TIPO_DOCUMENTO("Tipo de documento"),
    SISTEMA("Sistema"),
    MENU("Menú"),
    PERMISOS("Permisos"),
    TIPO_PACIENTE("Tipo de paciente"),
    PARAMETRO("Parámetro"),
    ASEGURADORA("Aseguradora"),
    COBERTURA("Cobertura"),
    POLIZA("Póliza"),
    PARENTESCO("Parentesco"),
    DIAGNOSTICO("Diagnóstico"),
    TIPO_USUARIO("Tipo de usuario"),
    USUARIO("Usuario"),
    PACIENTE("Paciente"),
    TIPO_INFORME("Tipo de informe"),
    TITULO_INFORME("Detalle de informe"),
    UNIDAD("Unidad"),
    FAMILIA("Familia"),
    PERSONA("Persona"),
    GENERICO("Genérico"),
    PRODUCTO("Producto"),
    FUNCION_FARMAC("Función farmacológica"),
    LABORATORIO("Laboratorio"),
    VACUNA("Vacuna"),
    PRESENTACION("Presentación"),
    PRODUCTO_NO_CUBIERTO("Producto no cubierto"),
    TIPO_ADMISION("Tipo de admisión"),
    OPERACION("Operación"),
    TARIFARIO("Tarifario"),
    POLIZA_PACIENTE("Poliza de paciente"),
    CITA("Cita"),
    PROGRAMACION_HORARIO("Programación de horarios"),
    SERVICIO("Servicio"),
    SERVICIO_CONTABLE("Servicio contable"),
    TARIFA_PARTICULAR("Tarifa particular"),
    TARIFA_SOCIAL("Tarifa social"),
    INFORME_MEDICO("Informe médico"),
    TARJETA_DESCUENTO("Tarjeta de descuento"),
    PARRAFO_INFORME("Parrafo informe"),
    HISTORIA_CLINICA("Historia clinica"),
    ALMACEN("Almacén"),
    BANCO("Banco"),
    ADMISION("Admisión"),
    ADMISION_MEDICO("Admisión médico"),
    TIPO_TARJETA_CREDITO("Tipo de tarjeta de crédito"),
    TIPO_DOCUMENTO_MOV("Tipo de documento movimiento"),
    CORRELATIVO_DOCUM("Correlativo de documento"),
    CIERRE_CAJA("Cierre de caja"),
    APERTURA_CAJA("Apertura de caja"),
    MONEDA("Moneda"),
    DOCUMENTO_CABECERA("Documento cabecera"),
    PROMOCION("Promoción"),
    POLIZA_COBERTURA("Poliza - cobertura"),
    PRODUCTO_PRECIO_ESPECIAL("Precio especial"),
    VENTA("Venta"),
    GUIA_INTERNA("Guía interna"),
    INVENTARIO("Inventario"),
    TIPO_TARJETA_DESCUENTO("Tipo de tarjeta de descuento"),
    INVENTARIO_TOTAL("Inventario total"),
    COBRANZA("Cobranza"),
    COBRANZA_ODONTOLOGIA("Cobranza de odontología"),
    UBIGEO("Ubigeo"),
    TIPO_UBIGEO("Tipo de ubigeo"),
    PAIS("País"),
    FERIADO("Feriado"),
    DOCUM_TRANSFERENCIA("Transferencia"),
    DOCUMENTO_ANULADO("Documento Anulado"),
    TIPO_CAMBIO("Tipo de Cambio"),
    COMPRA("Compra"),
    NOTA_CREDITO("Nota de crédito"),
    LIBRO_RECLAMACION("Libro de Reclamación"),
    ANALISIS_CATEGORIA("Categoria de análisis"),
    ANALISIS_TIPO("Tipo de análisis"),
    ANALISIS_ETAPA("Etapa de análisis"),
    ANALISIS_PARAMETRO("Parámetro de análisis"),
    ANALISIS_PARAMETRO_RESULTADO("Resultado de parámetro de análisis"),
    PREFACTURA_ASEGURADORA("Prefactura aseguradora"),
    LIQUIDACION_CABECERA("Liquidacion Cabecera"),
    LIQUIDACION_FACTURA("Liquidacion Factura"),
    LABORATORIO_ADMISION("Admisión de laboratorio"),
    RESULTADO_LABORATORIO("Resultado de laboratorio"),
    HOSP_CUARTO("Cuarto"),
    LOTE("Lote"),
    SEGUS_NO_CUBIERTO("Segus no cubierto"),
    TIPO_AFILIACION("Tipo de afiliación"),
    LIQUIDACION_DIARIA("Liquidacion diaria"),
    PORCENTAJE_DESCUENTO("Porcentaje de descuento"),
    PRODUCTO_SITEDS("Producto siteds"),
    ANALISIS_ETIQUETA("Etiqueta de analisis"),
    HOSPITALIZACION_PAGO_CUENTA("Pago a cuenta"),
    LIQUIDACION_HOSPITALIZACION("Liquidación de hospitalización/emergencia"),
    FACTURACION_HOSPITALIZACION("Facturación de hospitalización/emergencia"),
    FACTURAS_PAGADAS("Facturas pagadas"),
    ADMISION_HOSPITALIZACION("Admisión de hospitalización/emergencia"),
    PIEZA_DENTAL("Pieza dental"),
    FICHA_ATENCION_INTEGRAL("Ficha de atencion integral"),
    OPERACION_MEDICA("Operación médica"),
    HOSPITALIZACION_PRESTACION("Prestación de hospitalización"),
    TARIFA_FIJA("Tarifa fija");

    private String value;

    private NombreEntidadEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
