package enums;

public enum ParametroEnum {

    CONSULTA_AMBULATORIA_HONORARIO("CONSULT_AMBULATORIA_PART_HONOR"),
    HONORARIO_CORTESIA("HONORARIO_CORTESIA"),
    INF_MED_HISTORIA_CLINICA("INF_MED_HISTORIA_CLINICA"),
    TIPO_ADMISION_TOPICO("TIPO_ADMISION_TOPICO"),
    TIPO_ADMISION_VACUNAS("TIPO_ADMISION_VACUNAS"),
    TIPO_INF_HISTORIA_CLINICA("TIPO_INF_HISTORIA_CLINICA"),
    IGV("IGV"),
    VENTA_EFECTIVO_FARMACIA("VENTA_EFECTIVO_FARMACIA"),
    VENTA_CREDITO_FARMACIA("VENTA_CREDITO_FARMACIA"),
    ID_SERVICIO_FARMACIA("ID_SERVICIO_FARMACIA"),
    ID_SERVICIO_FARMACIA_INAFECTA("ID_SERVICIO_FARMACIA_INAFECTA"),
    ID_SERVICIO_TOPICO("ID_SERVICIO_TOPICO"),
    ID_SERVICIO_LABORATORIO("ID_SERVICIO_LABORATORIO"),
    ID_SERVICIO_IMAGENOLOGIA("ID_SERVICIO_IMAGENOLOGIA"),
    ID_SERVICIO_EMERGENCIA("ID_SERVICIO_EMERGENCIA"),
    ID_SERVICIO_CONSULTA_AMBULATORIA("ID_SERV_CONSLTA_AMBULAT"),
    ID_SERVICIO_PROCEDIMIENTOS("ID_SERVICIO_PROCEDIMIENTOS"),
    ID_SERVICIO_ODONTOLOGIA("ID_SERVICIO_ODONTOLOGIA"),
    ID_SERVICIO_HOTELERIA("ID_SERVICIO_HOTELERIA"),
    ID_SERVICIO_OTROS("ID_SERVICIO_OTROS"),
    ID_SERVICIO_CONTABLE_CONSULTA_MEDICA("ID_SERVICIO_CONTABLE_CONS_MED"),
    ID_SERVICIO_CONTABLE_FARMACIA("ID_SERVICIO_CONTABLE_FARMACIA"),
    ID_SERVICIO_CONTABLE_LABORATORIO("ID_SERV_CONT_LABORATORIO"),
    ID_SERVICIO_CONTABLE_RADIOGRAFIA("ID_SERV_CONT_RADIOGRAFIA"),
    ID_SERVICIO_CONTABLE_TOPICO("ID_SERV_CONT_TOPICO"),
    ID_SERVICIO_CONTABLE_ODONTOLOGIA("ID_SERV_CONT_ODONTOLOGIA"),
    VENTA_EFECTIVO_COBRANZA("VENTA_EFECTIVO_COBRANZA"),
    VENTA_CREDITO_COBRANZA("VENTA_CREDITO_COBRANZA"),
    ID_TIPO_DOC_MOV_BOLETA("ID_TIPO_DOC_MOV_BOLETA"),
    ID_TIPO_DOC_MOV_FACTURA("ID_TIPO_DOC_MOV_FACTURA"),
    ID_TIPO_DOC_MOV_NOTA_CREDITO("ID_TIPO_DOC_MOV_NOTA_CREDITO"),
    ID_TIPO_DOC_MOV_HOJA_SERV("ID_TIPO_DOC_MOV_HOJA_SERV"),
    ID_TIPO_DOC_MOV_HOJA_CONSUMO("ID_TIPO_DOC_MOV_HOJA_CONS"),
    ID_TIPO_DOC_GUIA_REMISION("ID_TIPO_DOC_GUIA_REMISION"),
    ID_TIPO_DOC_HOJAS_SEGURO_SIN_PAGO("ID_TIPO_DOC_HOJ_SEG_SIN_PAGO"),
    ID_TIPO_DOC_LOTE("ID_TIPO_DOC_LOTE"),
    ID_TIPO_DOC_DOC_INTERNO("ID_TIPO_DOC_DOC_INTERNO"),
    ID_TIPO_DOC_GUIA_INTERNA("ID_TIPO_DOC_GUIA_INTERNA"),
    ID_OPERACION_SALIDA_TRANSFERENCIA("ID_OP_SALIDA_TRANSF"),
    ID_OPERACION_INGRESO_TRANSFERENCIA("ID_OP_INGRESO_TRANSF"),
    ID_PAIS_PERU("ID_PAIS_PERU"),
    ID_ALMACEN_FARMACIA("ID_ALMACEN_FARMACIA"),
    DEVOLUCION_DE_CLIENTE_NOTA_CREDITO("OP_DEVOLUCION_CLIENTE_NC"),
    NOTA_CREDITO_GLOBAL("OPERACION_NC_GLOBAL"),
    ID_COBERTURA_CONTROL_NINO_SANO("ID_COBERTURA_CONTROL_NINO_SANO"),
    ID_COBERTURA_VACUNAS("ID_COBERTURA_VACUNAS"),
    IMPRESORA_MATRICIAL("IMPRESORA_MATRICIAL"),
    ID_OPERACION_VENTA_CREDITO("ID_OP_VENTA_CREDITO"),
    RUC_EMPRESA("RUC_EMPRESA"),
    DIAS_MAX_PARA_PRESTACION_SERVICIOS("DIAS_MAX_PRESTACION_SERV"),
    HORA_INICIO_HORARIO_NOCTURNO_LUN_VIE("HORA_INI_HN_LV"),
    HORA_INICIO_HORARIO_NOCTURNO_SAB("HORA_INI_HN_SAB"),
    HORA_INICIO_NORMAL("HORA_INI_NORMAL"),
    PORC_INCREM_ADMISION_HORARIO_NOCTURNO("PORC_INCREM_ADMISION_HOR_NOC"),
    ID_PARENTESCO_DEFAULT("ID_PARENTESCO_DEFAULT"),
    ID_DOCUMENTO_RUC("ID_DOCUMENTO_RUC"),
    CARACTERES_OBVIADOS("CARACTERES_OBVIADOS"),
    CARACTERES_REEMPLAZO_TRAMA("CARACTERES_REEMPLAZO_TRAMA"),
    CUENTA_CONTABLE_DEFAULT("CUENTA_CONTABLE_DEFAULT"),
    ID_MOTIVOS_CON_RETORNO_INVENTARIO("ID_MOTIVOS_CON_RETORNO_INVENT"),
    INCLUIR_CABECERA_LABORATORIO("INCLUIR_CABECERA_LABORATORIO"),
    PAGINA_EMPRESA("PAGINA_EMPRESA"),
    DIRECCION_EMPRESA("DIRECCION_EMPRESA"),
    TELEFONO_EMPRESA("TELEFONO_EMPRESA"),
    TIPO_DOCUMENTO_DEFAULT_SUNAT("TIPO_DOCUMENTO_DEFAULT_SUNAT"),
    NUMERO_DOCUMENTO_DEFAULT_SUNAT("NUMERO_DOCUMENTO_DEFAULT_SUNAT"),
    URL_SERVICIO_LLAMADAS_PACIENTES("URL_SERV_LLAMADAS_PACTS"),
    INVENTARIO_ACTUALIZACION("INVENTARIO_ACTUALIZACION"),
    PORCENTAJE_INCREMENTO_LAPAROSCOPICO("PORCT_INCR_LAPAROSCOPICO"),
    CODIGO_IPRESS("CODIGO_IPRESS");

    private final String value;

    private ParametroEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

}
