/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.unp.generadorpruebas.vista;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pe.edu.unp.generadorpruebas.modelo.CasoDePrueba;
import pe.edu.unp.generadorpruebas.modelo.Clase;
import pe.edu.unp.generadorpruebas.modelo.Metodo;
import pe.edu.unp.generadorpruebas.modelo.Prueba;
import pe.edu.unp.generadorpruebas.modelo.RecursoJava;
import pe.edu.unp.generadorpruebas.servicio.BusquedaSolucionesServicio;
import pe.edu.unp.generadorpruebas.servicio.CompilacionServicio;
import pe.edu.unp.generadorpruebas.servicio.ModeladoServicio;
import pe.edu.unp.generadorpruebas.servicio.PruebaServicio;
import pe.edu.unp.generadorpruebas.util.ResultadoComando;

@Component
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            LOGGER.error(ex, ex);
            ex.printStackTrace();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButton1)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        String rutaArchivo = "/home/nazaret/generador_pruebas/Programa.java";
        String rutaArchivo = "/home/nazaret/generador_pruebas/SegundaPrueba.java";
//        String rutaArchivo = "/home/nazaret/pruebas_generador/nomiproject";//<-exit value = 1
//        String rutaArchivo = "/home/nazaret/pruebas_generador/miproject";//<-exit value = 0

//        String nombreMetodo = "wait";
//        String nombreMetodo = "sumar2";
        String nombreMetodo = "metodo3";
        RecursoJava proyecto = modeladoServicio.obtenerProyecto(rutaArchivo);

        try {
            //1.- compilacion
            compilacionServicio.validarProgramaSeleccionado(rutaArchivo);
            Boolean compilar = compilacionServicio.compilar(proyecto);
            System.out.println(compilar);

            //2.- modelado
            Clase clase = (Clase) proyecto;
            Metodo metodo = modeladoServicio.obtenerMetodoEjecucion(clase, nombreMetodo);

            //3.- busqueda de soluciones optimas
            List<CasoDePrueba> solucionesOptimas;
            solucionesOptimas = busquedaSolucionesServicio.buscarSolucionesOptimas(metodo);
            //4.- Creacion de pruebas
            Prueba prueba;
            prueba = pruebaServicio.crearPruebas(metodo, solucionesOptimas);
            //5.- Ejecucion de pruebas
            ResultadoComando resultadoPruebas;
            resultadoPruebas = pruebaServicio.ejecutarPrueba(proyecto, prueba);
            //6.- Resultados
            //resultadoPruebas....
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    @Autowired
    private CompilacionServicio compilacionServicio;

    @Autowired
    private ModeladoServicio modeladoServicio;

    @Autowired
    private PruebaServicio pruebaServicio;

    @Autowired
    private BusquedaSolucionesServicio busquedaSolucionesServicio;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
